# Generated by Django 4.2.2 on 2023-07-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
