# Generated by Django 4.2.2 on 2023-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GSM',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
