# Generated by Django 4.2.2 on 2023-07-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='land',
            new_name='country',
        ),
    ]
