# Generated by Django 4.2.2 on 2023-07-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_land_userprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='plaatsnaam',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post_code',
        ),
    ]
