# Generated by Django 4.2.2 on 2023-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Bancontact', 'Bancontact'), ('Klarna', 'Klarna')], max_length=100),
        ),
    ]
