# Generated by Django 4.2.2 on 2023-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_alter_openinghour_from_hour_and_more'),
        ('orders', '0004_order_total_data_payment_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='vendors',
        ),
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
